# Generated by Django 5.1.1 on 2024-09-10 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
