# Generated by Django 5.1.1 on 2024-09-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_education_icon_alter_skill_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary', models.CharField(max_length=7)),
                ('secondary', models.CharField(max_length=7)),
                ('background', models.CharField(max_length=7)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
