# Generated by Django 5.1.1 on 2024-09-11 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='center',
            field=models.CharField(max_length=100, verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='education',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.URLField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='home.skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background',
            field=models.CharField(max_length=7, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary',
            field=models.CharField(max_length=7, verbose_name='Primary color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary',
            field=models.CharField(max_length=7, verbose_name='Secondary color'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='behance',
            field=models.URLField(blank=True, null=True, verbose_name='Behance'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.TextField(verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='dribbble',
            field=models.URLField(blank=True, null=True, verbose_name='Dribbble'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='experience',
            field=models.ManyToManyField(blank=True, to='home.experience', verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='open_to_work',
            field=models.BooleanField(default=True, verbose_name='Open to work'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='projects',
            field=models.ManyToManyField(blank=True, to='home.project', verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='show_email',
            field=models.BooleanField(default=True, verbose_name='Show email'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skills',
            field=models.ManyToManyField(blank=True, to='home.skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='studies',
            field=models.ManyToManyField(blank=True, to='home.education', verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='twitch',
            field=models.URLField(blank=True, null=True, verbose_name='Twitch'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
